### DISCUSSION TITLE
Do I need to update my deployment?

### DISCUSSION THREAD

**Discussion by HotCakeX** [serverless-dns/serverless-dns#149] [Q&A] [answered]
How often, if at all, do I need to update my deployments? I use Cloudflare worker and I only deployed it once months ago but I'm curious if you add new features, patches, fixes etc. to the project and if I need or if it's recommended to update my deployment on Cloudflare or even delete it and redeploy it.

Thanks

**Comment by PikachuJP** [comment]
I have same question

**Comment by ignoramous** [comment, marked as answer]
For Cloudflare Workers, you don't *really* have to update often, but I'd suggest updating it at least once a year. For deployments to Fly.io, I'd suggest keeping in sync with this repo, as performance improvements and optimizations are *still* on-going.

You should consider however re-deploying (the same code even) weekly / monthly to get the latest blocklists (which are updated on [1st / 8th / 16th / 24th of every month](https://github.com/serverless-dns/blocklists/blob/188f0565dc98242b49c9ac836009b9f0f343fdff/.github/workflows/createUploadBlocklistFilter.yml#L5-L6)).

For example, to deploy to Cloudflare Workers on 2nd / 9th / 17th / 25th, add to your `cf.yml` (or equivalent github actions config):

```
on:
  schedule:
    # why? github.com/serverless-dns/blocklists/blob/fe92d9b/.github/workflows/createUploadBlocklistFilter.yml#L5-L6
    # at 1:53 on 2nd, 9th, 17th, 25th of every month
    - cron: '53 1 2,9,17,25 * *'
```

Conditional blocklist update is done by [`src/build/pre.sh`](https://github.com/serverless-dns/serverless-dns/blob/77fead1b016496a9aadfd0e2911c138cda6dc0a3/src/build/pre.sh) invoked by the [`npm prepare`](https://github.com/serverless-dns/serverless-dns/blob/77fead1b016496a9aadfd0e2911c138cda6dc0a3/package.json#L14) step during [`npm install`](https://github.com/serverless-dns/serverless-dns/blob/77fead1b016496a9aadfd0e2911c138cda6dc0a3/.github/workflows/cf.yml#L91) in `cf.yml`.
