### ISSUE TITLE
Error when deploy to cloudflare worker in `Wrangler publish` step

### ISSUE THREAD

**Issue by SoraShu** [serverless-dns/serverless-dns#197]
Action logs:

>   ✘ [ERROR] More than one account available but unable to select one in non-interactive mode.
>   
>     Please set the appropriate `account_id` in your `wrangler.toml` file.
>     Available accounts are (`<name>`: `<account_id>`):
>       `XXX`: `xxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
>       `YYY`: `yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy`
>       `ZZZ`: `zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz`
>   
>   
>   If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
> Error: The process '/usr/local/bin/npx' failed with exit code 1
> Error: 🚨 Action failed

**Comment by SoraShu** [comment]
I try to fix it by adding `with.accountId` in Wrangler push step and it works.

```
      - name: 📚 Wrangler publish
        # github.com/cloudflare/wrangler-action
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          # input overrides env-defaults, regardless
          environment: ${{ env.WORKERS_ENV }}
        env:
          # CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          GIT_COMMIT_ID: ${{ env.COMMIT_SHA }}
```
